%---------------------------------------------------------------------------------------------------
% For Paper
% "Robust Performance Analysis of Source-Seeking Dynamics with Integral Quadratic Constraints"
% by Adwait Datar and Herbert Werner
% Copyright (c) Institute of Control Systems, Hamburg University of Technology. All rights reserved.
% Licensed under the GPLv3. See LICENSE in the project root for license information.
% Author(s): Adwait Datar
%---------------------------------------------------------------------------------------------------
function [G]=define_G_planar_quadrotor_wrapped(dim,kd,kp)
% This function defines a closed-loop vehicle model that has flocking force
% as input and position and velocity as output
% General LTI vehicle models should be in the form 1/s*G_vel where G_vel is
% a velocity tracking controller.

%% Generic second order vehicle: mass with friction in 1D
g=9.8; m=1; I_xz=1;

A=[0,       0,      0,      1,      0,      0;...
   0,       0,      0,      0,      1,      0;...
   0,       0,      0,      0,      0,      1;...
   0,       0,      -g,     0,      0,      0;...
   0,       0,      0,      0,      0,      0;...
   0,       0,      0,      0,      0,      0];
B=[0,       0;...
   0,       0;...
   0,       0;...
   0,       0;...
   1/m,     0;...
   0,       1/I_xz];
C=[1,0,0,0,0,0;...
   0,1,0,0,0,0];
D=zeros(2);

G=ss(A,B,C,D);
end